In [1]:
import numpy as np
import pandas as pd

In [2]:
np.load('iPhoneCam.npz')

NpzFile 'iPhoneCam.npz' with keys: tvecs, mtx, dist, rvecs

In [3]:
data = np.load('iPhoneCam2.npz')

In [4]:
array1 = data['tvecs']
array2 = data['mtx']
array3 = data['dist']
array4 = data['rvecs']

In [5]:
array1

array([[[-5.2516883 ],
        [-1.01843617],
        [64.29108416]],

       [[-2.36021   ],
        [ 0.86892611],
        [86.44007548]],

       [[-5.79188177],
        [-1.14473442],
        [47.70369274]],

       [[-1.90990013],
        [-5.80492642],
        [71.55984907]],

       [[-6.36738923],
        [-3.06912389],
        [77.71935018]],

       [[ 0.56669036],
        [-8.54288753],
        [75.36882281]],

       [[ 2.51875482],
        [-4.77845699],
        [76.91445662]],

       [[-2.61749533],
        [-1.7151796 ],
        [76.52889888]],

       [[ 2.06029675],
        [-1.46208066],
        [79.24217198]]])

In [6]:
array2

array([[2.40177696e+03, 0.00000000e+00, 1.19697209e+03],
       [0.00000000e+00, 2.41740503e+03, 1.61438047e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [7]:
array3

array([[-6.96722305e+00,  3.96768714e+02,  3.39833920e-02,
        -7.45673446e-03, -6.94753468e+03]])

In [8]:
array4

array([[[ 0.10752774],
        [-0.0655603 ],
        [ 0.1785193 ]],

       [[-0.12608557],
        [ 0.19722191],
        [ 0.58855878]],

       [[ 0.05119932],
        [-0.11935447],
        [-0.15866799]],

       [[-0.59488073],
        [ 0.13389567],
        [ 0.61691502]],

       [[-0.24132594],
        [-0.35236724],
        [-1.53652087]],

       [[-0.35782728],
        [ 0.37861728],
        [ 1.52917407]],

       [[-0.29738919],
        [ 0.49288618],
        [ 2.41177235]],

       [[-0.16509956],
        [-0.51950922],
        [-2.2173405 ]],

       [[ 0.07939303],
        [-0.52889724],
        [-2.98726412]]])

In [9]:
np.load('iPhoneCam2.npz')

NpzFile 'iPhoneCam2.npz' with keys: mtx, dist, rvecs, tvecs